sudo: false
language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.1

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
